# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Timescale
    orgId: 1
  - name: Loki
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  # <string, required> name of the datasource. Required
- name: Timescale
  # <string, required> datasource type. Required
  type: postgres
  # <string, required> access mode. direct or proxy. Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: http://db:5432
  # <string> database password, if used
  password:
  # <string> database user, if used
  user: root
  # <string> database name, if used
  database: homer_data
  # <bool> enable/disable basic auth
  basicAuth: false
  # <bool> mark as default datasource. Max one per org
  isDefault: true
  # <map> fields that will be converted to json and stored in json_data
  jsonData:
     postgresVersion: 1000
     sslmode: "disable"
     timescaledb: true
  # <string> json object of data that will be encrypted.
  secureJsonData:
    tlsCACert: "..."
    tlsClientCert: "..."
    tlsClientKey: "..."
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: true

- name: Loki
  type: loki
  access: proxy
  url: http://loki:3100
  editable: true
