version: '2.1'

volumes:
    postgres_data: {}
    influx_data: {}
    grafana_data: {}
    loki_data: {}

services:
  caddy:
    image: stefanprodan/caddy
    #container_name: caddy
    ports:
      - "3000:3000"
      - "9090:9090"
      - "9080:9080"
    volumes:
      - ./caddy/:/etc/caddy/
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-sipcapture}
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"
    networks:
        homer.server:

  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: homerSeven
      POSTGRES_USER: root
    expose:
      - 5432
    restart: unless-stopped
    volumes:
      - ./conf/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "psql -h 'localhost' -U 'root' -c '\\l'"]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
        homer.server:

  heplify-server:
    image: sipcapture/heplify-server:master
    #container_name: heplify-server
    ports:
      - "9060:9060"
      - "9060:9060/udp"
    command:
      - './heplify-server'
    environment:
      - "HEPLIFYSERVER_HEPADDR=0.0.0.0:9060"
      - "HEPLIFYSERVER_DBDRIVER=postgres"
      - "HEPLIFYSERVER_DBSHEMA=homer7"
      - "HEPLIFYSERVER_DBADDR=db:5432"
      - "HEPLIFYSERVER_DBUSER=root"
      - "HEPLIFYSERVER_DBPASS=homerSeven"
      - "HEPLIFYSERVER_DBDATATABLE=homer_data"
      - "HEPLIFYSERVER_LOGLVL=info"
      - "HEPLIFYSERVER_LOGSTD=true"
      - "HEPLIFYSERVER_PROMADDR=0.0.0.0:9096"
      - "HEPLIFYSERVER_PROMTARGETIP="
      - "HEPLIFYSERVER_PROMTARGETNAME="
      - "HEPLIFYSERVER_DBDROPDAYS=7"
      - "HEPLIFYSERVER_DEDUP=false"
      - "HEPLIFYSERVER_LOKIURL=http://loki:3100/api/prom/push"
      - "HEPLIFYSERVER_LOKITIMER=2"
    restart: unless-stopped
    expose:
      - 9060
    depends_on:
     db:
       condition: service_healthy
    labels:
      org.label-schema.group: "monitoring"
    networks:
        homer.server:

  homer-webapp:
          #container_name: homer-webapp
    image: sipcapture/homer-app:master
    environment:
      - "DB_HOST=db"
      - "DB_USER=root"
      - "DB_PASS=homerSeven"
    expose:
      - 80
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
        homer.server:

  telegraf:
    image: telegraf:alpine
    restart: unless-stopped
    volumes:
      - ./conf/telegraf.conf:/etc/telegraf/telegraf.conf
    ports:
      - "8092:8092/udp"
      - "8125:8125/udp"
    depends_on:
      - heplify-server
    networks:
        homer.server:

  influxdb:
    image: influxdb:alpine
    volumes:
      - influx_data:/var/lib/influxdb
    expose:
      - 8086
    networks:
        homer.server:

  chronograf:
    image: chronograf:alpine
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    expose:
      - 8888
    links:
      - influxdb
      - kapacitor
    networks:
        homer.server:

  kapacitor:
    image: kapacitor:alpine
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    links:
      - influxdb
    expose:
      - 9092
    networks:
        homer.server:

  grafana:
    image: grafana/grafana:master
    links:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-sipcapture}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_EXPLORE_ENABLED=true
    restart: unless-stopped
    expose:
      - 3000
    networks:
      homer.server:

  loki:
    image: grafana/loki:master
    #container_name: loki
    volumes:
      - ./loki/loki-local-config.yaml:/etc/loki/loki-local-config.yaml
      - loki_data:/data/loki
    restart: unless-stopped
    expose:
      - 3100
    ports:
      - "3100:3100"
    command: "-config.file=/etc/loki/loki-local-config.yaml"
    labels:
      org.label-schema.group: "monitoring"
    networks:
      homer.server:

  provisioning:
    image: alpine:latest
    links:
      - influxdb
      - chronograf
    depends_on:
      - influxdb
      - chronograf
    volumes:
      - ./conf/homer_dashboard.json:/tmp/homer_dashboard.json
    command: 
      - /bin/sh
      - -c
      - |
        apk add --no-cache curl;
        echo Waiting for influxdb API ...;
        while ! nc -z influxdb 8086;
        do
          sleep 1;
        done;
        echo InfluxDB Retention Policy push ...;
        curl -G http://influxdb:8086/query --data-urlencode 'q=CREATE DATABASE homer'
        curl -G http://influxdb:8086/query --data-urlencode 'q=CREATE RETENTION POLICY "60s" ON "homer" DURATION 4w REPLICATION 1 DEFAULT'
        curl -G http://influxdb:8086/query --data-urlencode 'q=CREATE RETENTION POLICY "300s" ON "homer" DURATION 8w REPLICATION 1'
        curl -G http://influxdb:8086/query --data-urlencode 'q=CREATE RETENTION POLICY "3600s" ON "homer" DURATION 16w REPLICATION 1'
        curl -G http://influxdb:8086/query --data-urlencode 'q=CREATE RETENTION POLICY "86400s" ON "homer" DURATION 32w REPLICATION 1'
        curl -G http://influxdb:8086/query --data-urlencode 'q=CREATE CONTINUOUS QUERY cq_300s ON homer RESAMPLE EVERY 1m BEGIN SELECT mean(*) INTO homer."300s".:MEASUREMENT FROM homer."60s"./.*/ GROUP BY time(5m),* END'
        curl -G http://influxdb:8086/query --data-urlencode 'q=CREATE CONTINUOUS QUERY cq_3600s ON homer RESAMPLE EVERY 10m BEGIN SELECT mean(*) INTO homer."3600s".:MEASUREMENT FROM homer."60s"./.*/ GROUP BY time(1h),* END'
        curl -G http://influxdb:8086/query --data-urlencode 'q=CREATE CONTINUOUS QUERY cq_86400s ON homer RESAMPLE EVERY 1h BEGIN SELECT mean(*) INTO homer."86400s".:MEASUREMENT FROM homer."60s"./.*/ GROUP BY time(1d),* END'
        curl -G http://influxdb:8086/query --data-urlencode 'q=drop retention policy "autogen" ON "homer"'
        while ! nc -z chronograf 8888;
        do
          sleep 1;
        done;
        echo Chronograf Dashboard push ...;
        curl -i -X POST -H "Content-Type: application/json" http://chronograf:8888/chronograf/v1/dashboards -d @/tmp/homer_dashboard.json
        echo Provisioning completed! Exiting ...;
        poweroff;
    networks:
      homer.server:


  hepgen:
    image: sipcapture/hepgenjs:master
    depends_on:
      - homer-webapp
      - heplify-server
    command:
      - /bin/sh
      - -c
      - |
        sleep 30
        node hepgen.js -s 172.17.0.1 -a 172.17.0.1 -c ./config/b2bcall_rtcp_log.js
        echo "HEPGEN Complete!"
    networks:
      homer.server:


# Custom network so all services can communicate using a FQDN
networks:
    homer.server:
