version: '2.1'

services:
  caddy:
    container_name: caddy
    image: stefanprodan/caddy
    container_name: caddy
    ports:
      - "3000:3000"
      - "9090:9090"
      - "9093:9093"
      - "9080:9080"
    volumes:
      - ./caddy/:/etc/caddy/
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: homerSeven
      POSTGRES_USER: root
    expose:
      - 5432
    restart: unless-stopped
    volumes:
      - ./conf/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "psql -h 'localhost' -U 'root' -c '\\l'"]
      interval: 1s
      timeout: 3s
      retries: 30

  heplify-server:
    image: sipcapture/heplify-server:master
    container_name: heplify-server
    ports:
      - "9060:9060"
      - "9060:9060/udp"
    command:
      - './heplify-server'
    environment:
      - "HEPLIFYSERVER_HEPADDR=0.0.0.0:9060"
      - "HEPLIFYSERVER_DBDRIVER=postgres"
      - "HEPLIFYSERVER_DBSHEMA=homer7"
      - "HEPLIFYSERVER_DBADDR=db:5432"
      - "HEPLIFYSERVER_DBUSER=root"
      - "HEPLIFYSERVER_DBPASS=homerSeven"
      - "HEPLIFYSERVER_DBDATATABLE=homer_data"
      - "HEPLIFYSERVER_LOGLVL=info"
      - "HEPLIFYSERVER_LOGSTD=true"
      - "HEPLIFYSERVER_PROMADDR=0.0.0.0:9096"
      - "HEPLIFYSERVER_PROMTARGETIP="
      - "HEPLIFYSERVER_PROMTARGETNAME="
      - "HEPLIFYSERVER_DBDROPDAYS=7"
    restart: unless-stopped
    expose:
      - 9090
    depends_on:
     db:
       condition: service_healthy
    labels:
      org.label-schema.group: "monitoring"

  homer-webapp:
    container_name: homer-webapp
    image: sipcapture/homer-app:master
    environment:
      - "DB_HOST=db"
      - "DB_USER=root"
      - "DB_PASS=homerSeven"
    expose:
      - 8001
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  telegraf:
    image: telegraf:1.5-alpine
    restart: unless-stopped
    volumes:
      - ./conf/telegraf.conf:/etc/telegraf/telegraf.conf
    ports:
      - "8092:8092/udp"
      - "8125:8125/udp"
    depends_on:
      - heplify-server

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.1
    container_name: elasticsearch
    environment: ['http.host=0.0.0.0', 'transport.host=127.0.0.1']
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.3.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  hepsub-elastic:
    container_name: hepsub-elastic
    image: sipcapture/hepsub-elastic
    environment:
      - PUBLIC_IP=${PUBLIC_IP:-hepsub-elastic}
      - PUBLIC_PORT=${PUBLIC_PORT:-18088}
      - HOMER_IP=${HOMER_IP:-homer-webapp}
      - HOMER_PORT=${HOMER_PORT:-9080}
      - API_URL=${API_URL:-http://elasticsearch:9200}
    ports:
      - "18088:18088/tcp"
    depends_on:
      - elasticsearch
      - homer-webapp
